// Package manual_audit_test contains tests written manually after auditing the
// suites generated by AI. They intentionally describe business rules that the
// current production code does not satisfy, so they are expected to fail until
// support for Conjured items is implemented.
package manual_audit_test

import (
	"testing"

	"github.com/emilybache/gildedrose-refactoring-kata/gildedrose"
)

func TestConjuredItemsDegradeTwiceAsFast(t *testing.T) {
	tests := []struct {
		name        string
		sellIn      int
		quality     int
		wantSellIn  int
		wantQuality int
	}{
		{
			name:        "before sell date loses two quality points",
			sellIn:      3,
			quality:     6,
			wantSellIn:  2,
			wantQuality: 4,
		},
		{
			name:        "on sell date loses four quality points",
			sellIn:      0,
			quality:     6,
			wantSellIn:  -1,
			wantQuality: 2,
		},
		{
			name:        "degradation after sell date stops at zero",
			sellIn:      0,
			quality:     3,
			wantSellIn:  -1,
			wantQuality: 0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			item := &gildedrose.Item{
				Name:    "Conjured Mana Cake",
				SellIn:  tt.sellIn,
				Quality: tt.quality,
			}

			gildedrose.UpdateQuality([]*gildedrose.Item{item})

			if item.SellIn != tt.wantSellIn {
				t.Errorf("SellIn = %d; want %d", item.SellIn, tt.wantSellIn)
			}
			if item.Quality != tt.wantQuality {
				t.Errorf("Quality = %d; want %d", item.Quality, tt.wantQuality)
			}
		})
	}
}
